Repository nextcloud-libraries/nextcloud-router, pull requests merged in 2023-06, with the labels that each got.

#485 fix: Do not export the declaration of `window.OC`
  lib/index.ts
  lib/oc.d.ts
Labels: bug, 3. to review

#491 chore: update NC typings versions
  lib/oc.d.ts
  package-lock.json
  package.json
Labels: dependencies, technical debt

#493 chore: update node engines to next LTS
  package.json
Labels: dependencies, automated, 3. to review
