Repository nextcloud-libraries/nextcloud-router, pull requests merged in 2024-01, with the labels that each got.

#560 fix: Do not rely on `OC.webroots` or `OC.appwebroots` but use own logic
  lib/index.ts
  lib/oc.d.ts
Labels: bug, 3. to review

#559 chore: Update NPM version to 10 to align with version shipped by LTS Node 20
  package-lock.json
  package.json
Labels: dependencies, 3. to review

#562 chore: Prepare new release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#561 chore: Add ESLint to project and fix issues reported
  .eslintrc.json
  .github/workflows/lint-eslint.yml
  babel.config.js
  lib/index.ts
  package-lock.json
  package.json
Labels: 3. to review

#563 Drop `core-js` and move to vite
  babel.config.js
  lib/index.ts
  lib/oc.d.ts
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
Labels: 3. to review

#564 enh(tests): Add unit tests and CI workflow for testing
  .github/workflows/node-test.yml
  __tests__/paths.spec.ts
  __tests__/tsconfig.json
  __tests__/urls.spec.ts
  __tests__/webroot.spec.ts
  lib/index.ts
  package-lock.json
  package.json
  tsconfig.json
  vitest.config.ts
Labels: enhancement, 3. to review

#558 feat: add method to get a base URL, allow to pass remote base
  __tests__/urls.spec.ts
  __tests__/webroot.spec.ts
  lib/index.ts
Labels: enhancement, 3. to review

#566 fix: Adjust `generateFilePath` to include `type` also for `index.php`
  __tests__/paths.spec.ts
  lib/index.ts
Labels: bug, 3. to review

#569 Make README a bit nicer by adding badges for coverage and documentation
  README.md
Labels: 3. to review

#565 Clean up code (drop unreachable code) and minor modernization
  __tests__/paths.spec.ts
  lib/index.ts
Labels: bug, 3. to review

#570 fix(getRootUrl)!: If not configured use first subdirectory as webroot instead of last
  __tests__/webroot.spec.ts
  lib/index.ts
Labels: bug, 3. to review
